import Head from "next/head";
import AboutUs from "../components/aboutus";
import Header from "../components/header";
import Welcome from "../components/welcome";
import Recruit from "../components/recruit";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Placement Cell, DCSA-PU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Welcome />
        <AboutUs />
        <Recruit />
      </main>
      {/* <footer >
      </footer> */}
    </div>
  );
}
