import Head from 'next/head'
import Header from '../components/header'
import Welcome from '../components/welcome'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Placement Cell, DCSA-PU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Welcome />
      </main>

      {/* <footer >
      </footer> */}
    </div>
  )
}
