import Head from 'next/head'
import AboutUs from '../components/aboutus'
import Header from '../components/header'
import Welcome from '../components/welcome'
import Recruit from '../components/whyus'
import PastRecruit from '../components/pastrecruiter'
import Stats from '../components/stats'
import ContactUs from '../components/contactus'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Placement Cell, DCSA-PU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Welcome />
        <AboutUs />
        <Recruit />
        <PastRecruit />
        <Stats />
        <ContactUs />
      </main>
      {/* <footer >
      </footer> */}
    </div>
  )
}
